config/routes.rb
Rails.application.routes.draw do
  # Defines the root path route ("/")

  #New root: Jose Melendez
  root :to => 'dashboard#index'
  #

  #root :to => 'home#index'

  resources :providers

  #New Dashboard

  get 'dashboard(/:_id)', to: 'dashboard#index', as: 'dashboard';

  get 'dashboard/measure-result/:values', to: 'dashboard#measure_result', as: 'dashboard_measure_result'

  get 'dashboard/measure-result/patient-details/:patient_id', to: 'dashboard#patient_details', as: 'dashboard_patient_details'

  #add Jose Melendez, 10/23/2023
  resources :measures

  #
  apipie

  # devise_for :users, :controllers => {:registrations => "registrations"}
  devise_for :users, :controllers => {
    :registrations => "registrations",

    #change by Jose Melendez:
    #before:
    #:omniauth_callbacks => 'azure_auth/omniauth_callbacks'
    #after:
    :omniauth_callbacks => 'azure/omniauth_callbacks'  
    
    #:omniauth_callbacks => 'users/omniauth_callbacks' 
  }

  devise_scope :user do
    get '/users/sign_out' => 'devise/sessions#destroy' # This was neccesary, DELETE method is not working as intended
    #change by Jose Melendez:
    # get 'azure_auth/processLogin', to: 'azure_auth/omniauth_callbacks#logout_from_ad'
    get 'azure/processLogin', to: 'azure/omniauth_callbacks#logout_from_ad'

  end

  resources :practices

  resources :practices do
    collection do
      get :search
    end
  end

  get 'home/check_authorization'
  post 'home/set_reporting_period'
  
  #add Jose Melendez:
  post "dashboard/set_reporting_period"
  get "admin/users"
  post "admin/promote"
  post "admin/demote"
  post "admin/approve"
  post "admin/disable"
  post "admin/update_npi"
  get "admin/patients"
  get "admin/jobs"
  get "admin/providers"
  put "admin/upload_patients"
  put "admin/upload_providers"
  delete "admin/remove_patients"
  delete "admin/remove_caches"
  delete "admin/remove_providers"
  delete "admin/remove_all"
  delete "admin/remove_jobs"
  get "admin/user_profile"
  delete "admin/delete_user"
  post 'admin/set_user_practice'
  post 'admin/set_user_practice_provider'
  
  delete "practices/:id/remove_patients", :to => 'practices#remove_patients', as: :practices_remove_patients
  delete "practices/:id/remove_providers", :to => 'practices#remove_providers', as: :practices_remove_providers

  post "teams/:id/update", :to => 'teams#update'
  post "teams/create"
  post "teams/create_default"

  get 'teams/show_by_id/:id', to: 'teams#show_by_id', as: :show_team_by_id

  namespace :admin do

    resource :caches do
      collection do
        get :count

        #Edit Jose Melendez (descomentar)
        #get :spinner
        #get :static_measure
        #get 'static_measure/:id', :to => :static_measure
        #
      end
    end


    #Add Jose Melendez, 10/17/2023
    get "patients/patient_count", to: "patients#patient_count", defaults: { format: :json }
    

    resource :patients do
      collection do
        get :count
      end
    end
    resource :providers do
      collection do
        get :count
      end
    end
    resources :users do
      member do
        get :enable
        get :disable
        post :promote
        post :demote
        get :approve
        get :update_npi
      end
    end
  end

  resources :providers do
    resources :patients do
      collection do
        get :manage
        put :update_all
      end
    end

    get :measure_baseline

    member do
      get :merge_list
      put :merge
    end
  end

  resources :teams
  
  get "logs/index"

  namespace :api do
    
    resource :reports do
      get '*cat1.zip', :to =>'reports#cat1_zip', :format => :zip
      get 'cat1/:id/:measure_ids', :to =>'reports#cat1', :format => :xml
      get '*qrda_cat3.xml', :to =>'reports#cat3', :format => :xml
      get 'measures_spreadsheet', :to =>'reports#measures_spreadsheet'
      get 'patients', :to => 'reports#patients'
      get 'teams/team_providers/:id', :to => 'teams#team_providers'
      get 'team_report', :to => 'reports#team_report'
    end

    # The OID may contain periods, so specify a regex to allow that
    get 'value_sets/:oid', :to => 'value_sets#show', :oid => /([^\/])+?/, :format => :json

    resources :practices do
      collection do
        get :search
      end
    end

    resources :practices
    resources :teams

    resources :providers do
      collection do
        get :search
      end
      
      resources :patients do
        collection do
          get :manage
          put :update_all
        end
      end

    end

    resources :measures

    resources :queries do
      member do
       get :patients
       get :patient_results
       put :recalculate
       post :filter
       post :clearfilters
      end
    end

    namespace :admin do

      resource :caches do
        collection do
          get :count
          get :show_all
          #get :spinner REMOVE ME
          #get :static_measure REMOVE ME
          #get 'static_measure/:id', :to => :static_measure REMOVE ME
        end
      end

      resource :patients do
        collection do
          get :count
        end
      end

      resource :providers do
        collection do
          get :count
        end
      end

      resources :users do
        member do
          get :enable
          get :disable
          post :promote
          post :demote
          get :approve
          get :update_npi
        end
      end
    end
  end

  resources :patients do
    member do
      get :results
    end
  end

  namespace :api do
    resources :patients#, only: [:index, :show, :create]
  end



  # config/routes.rb


end

app/views/admin/__users_old.html.erb
<script type="text/javascript">
  var popHealth = popHealth || {};

  popHealth.promoteUser = function() {
    var username = $(this).data("username");
    var role = $(this).data("role");
    var parentTd = $(this).parent();
    $.post('<%= admin_promote_path %>', {'username': username, 'role': role}, function(data) {
      parentTd.html(data);
      parentTd.find('.demote').click(popHealth.demoteUser);
    });
    return false;
  };

  popHealth.demoteUser = function() {
    var username = $(this).data("username");
    var role = $(this).data("role");
    var parentTd = $(this).parent();

    if (username == '<%= current_user.username %>') {
      var response = confirm('You are about to remove admin rights from the currently logged in user' 
      +', this will cause you to immediately lose access to all admin functionality including this page.  ' 
      +'You will need to use another admin account to restore admin rights.  Are you sure you want to continue?');
      if (!response) return;
    }

    $.post('<%= admin_demote_path %>', {'username': username, 'role': role}, function(data) {
      parentTd.html(data);
      parentTd.find('.promote').click(popHealth.promoteUser);
    });
    return false;
  };

  popHealth.approveUser = function() {
    var username = $(this).data("username");
    var parentTd = $(this).parent();
    $.post('<%= admin_approve_path %>', {'username': username}, function(data) {
      parentTd.html(data);
    });
  };

  popHealth.disableUser = function() {
    var username = $(this).data("username");
    var parentTd = $(this).parent();

    if (username == '<%= current_user.username %>') {
      var response = confirm('You are about to disable the currently logged in user' 
      +', this will cause you to immediately lose access and be logged out.  Are you sure you want to continue?');
      if (!response) return;
    }

    popHealth.disableEnableUser(1, username, parentTd)
  };
  popHealth.enableUser = function() {
    var username = $(this).data("username");
    var parentTd = $(this).parent();
    popHealth.disableEnableUser(0, username, parentTd)
  };
  popHealth.disableEnableUser = function(disabled, username, parentTd) {
    $.post('<%= admin_disable_path %>', {'username': username, 'disabled': disabled}, function(data) {
      parentTd.html(data);
      if (disabled == 1) parentTd.find('.disable').click(popHealth.enableUser);
      else parentTd.find('.enable').click(popHealth.disableUser);
    });
  };
  popHealth.changeNpi = function() {
    var username = $(this).data("username");
    var npi = $(this).val();
    $.post('<%= admin_update_npi_path %>', {'username': username, 'npi': npi}, function(data) {
    });
    
  };
  
  popHealth.changePractice = function() {
    var userId = $(this).data("user");
    var practice = $(this).val();

    console.log(practice)
    var confs = "Change user's assigned practice?";   
    if ( confirm(confs) == true ){
      $.post('set_user_practice', {'user': userId, 'practice': practice}, function(d){
      }); 
    };
  };
  
  popHealth.changePracticeProvider = function() {
    var userId = $(this).data("user");
    var provider = $(this).val();
    var confs = "Change user's assigned provider?";   
    if ( confirm(confs) == true ){
      $.post('set_user_practice_provider', {'user': userId, 'provider': provider}, function(d){
      }); 
    };
  };

  $(document).ready(function() {
    $('.promote').click(popHealth.promoteUser);
    $('.demote').click(popHealth.demoteUser);
    $('.approve').click(popHealth.approveUser);
    $('.enable').click(popHealth.disableUser);
    $('.disable').click(popHealth.enableUser);
    $('.npi_select').change(popHealth.changeNpi);
    $('.practice_select').change(popHealth.changePractice);
    $('.practice_provider_select').change(popHealth.changePracticeProvider);
  });
</script>



<div id="pageContent" class="col-md-12">
<%= if !APP_CONFIG['use_opml_structure'] then link_to "Edit Practices", practices_path, :class => "btn btn-large btn-success pull-right practice-btn" end %>

<h1>Users</h1>
<table id="patientTable" class="table table-hover">
  <thead>
    <tr>
      <th>First Names</th>
      <th>Last Name</th>
      <th>Username</th>
      <% if APP_CONFIG['use_opml_structure'] %>
      <th>Provider</th>
      <% else %>
      <th>Practice</th>
      <th>Provider</th>
      <% end %>
      <th>Administrator</th>
      <th>Staff Role</th>
      <th>Approved</th>
      <th>Status</th>
      <th colspan="2"/>
    </tr>
  </thead>
  <% @users.each do |user| -%>
  <tbody>
  <tr>
    <td><%= user.first_name %></td>
    <td><%= user.last_name %></td>
    <td><%= user.username %></td>

    <% if APP_CONFIG['use_opml_structure'] %>
    <td>
      <select class="npi_select" data-username="<%= user.username %>" name="user[npi]">
        <option value="-1">&nbsp;</option>
        <% Provider.all.alphabetical.each do |provider| %>
          <option value="<%= provider.npi %>" <%= (user.npi == provider.npi) ? "selected=\"selected\"" : ""%>><%= provider.full_name %> </option>
        <% end%>
      </select>
    </td>
    <% else %>
      <td> 
        <% if Provider.valid_npi?(user.npi) %>
          N/A
        <% else %>
        <%= select_tag "practice", options_for_select(@practices, user.practice_id), prompt: 'None', data: {user: user.id.to_s}, class: 'practice_select'%> 
        <% end %>
      </td>
      

      <td> 
        <% if Provider.valid_npi?(user.npi) %>
        <% @practice_pvs = Provider.by_npi(user.npi).map {|pv| if pv.try(:parent).try(:practice) then [pv.parent.practice.name + " - " + pv.full_name, pv.id] end}%>
        <%= select_tag "practice_provider_select", options_for_select(@practice_pvs, user.provider_id), prompt: 'None', data: {user: user.id.to_s}, class: 'practice_provider_select'%> 
        <% else %>
          N/A
        <% end %>
      </td>

    <% end %>
    <td>
      <% if user.admin? -%>
      Yes - <a href="#" class="demote" data-role="admin" data-username="<%= user.username %>">revoke</a>
      <% else -%>
      No - <a href="#" class="promote" data-role="admin" data-username="<%= user.username %>">grant</a>
      <% end -%>
    </td>
    <td>
      <% if Provider.valid_npi?(user.npi) %>
        N/A
      <% else %>
        <% if user.staff_role? -%>
        Yes - <a href="#" class="demote" data-role="staff_role" data-username="<%= user.username %>">revoke</a>
        <% else -%>
        No - <a href="#" class="promote" data-role="staff_role" data-username="<%= user.username %>">grant</a>
        <% end -%>
      <% end %>
    </td>
    <td>
      <% if user.approved? -%>
      true
      <% else -%>
      <a href="#" class="approve" data-username="<%= user.username %>">approve</a>
      <% end -%>
    </td>
    <td>
      <a href="#" class="<%= (user.disabled?) ? 'disable' : 'enable'%>" data-username="<%= user.username %>"><%= (user.disabled?) ? 'disabled' : 'enabled'%></a>
    </td>
    <td>
      <%= link_to "View Info",{:controller => "admin", :action => "user_profile", :id => user._id}, :class => "btn btn-info"%>    
      <%= link_to "Delete User", {:controller => "admin", :action => "delete_user", :id => user._id}, 'method' => 'delete', 'class' => 'btn btn-danger delete-user-btn', data: {'confirm' => "Are you sure you want to delete this user?"} %>    			  
    </td>
  </tr>
  </tbody>
  <% end -%>
</table>
</div> <!-- pageContent -->

app/views/admin/_jobs.html.erb
<div id="pageContent" style="padding:20px;">
  <h3>Background Jobs</h3>

  <table width="500px">
    <tr>
      <td colspan="2">Total jobs:</td>
      <td><%= @job_count %> jobs</td>
      <td>
        <%= button_to "Delete All Jobs", "/admin/remove_jobs", 'method' => 'delete', 'class' => 'btn btn-danger'%>
      </td>
    </tr>
    <tr>
      <td>&nbsp;</td>
      <td>Measure Calculation:</td>
      <td><%= @calculation_job_count%> jobs</td>
      <td>&nbsp;</td>
    </tr>
    <tr>
      <td>&nbsp;</td>
      <td>Patient Import:</td>
      <td><%= @patient_job_count%> jobs</td>
      <td>&nbsp;</td>
    </tr>
  </table>
</div> <!-- pageContent -->

app/views/admin/patients.html.erb
<div data-controller="patients" class="col-md-12">

    <div class="col-md-12">

                <div class="panel panel-primary">

                    <div class="panel-heading">
                        <h3 class="panel-title"><span class="glyphicon glyphicon-user" aria-hidden="true"></span> Data Patients</h3>
                    </div>

                <div class="panel-body">

                    <table class="table table-bordered">
                        <thead>
                            <tr>
                                <th>Description</th>
                                <th style="width:10%;">Count</th>
                            </tr>
                        </thead>
                        <tbody>
                            <tr>
                                <td>Patients loaded</td>
                                <td id="patient_count"><%= @patient_count %></td>
                            </tr>
                            <tr>
                                <td>Providers loaded</td>
                                <td><%= @provider_count %></td>
                            </tr>
                            <% if !APP_CONFIG["use_opml_structure"] %>
                            <tr>
                                <td>Practices</td>
                                <td><%= @practice_count %></td>
                            </tr>
                            <% end %>
                            <tr>
                                <td>Query cache count</td>
                                <td><%= @query_cache_count %></td>
                            </tr>
                            <tr>
                                <td>Patients cache count</td>
                                <td><%= @patient_cache_count %></td>
                            </tr>
                        </tbody>
                    </table>

                </div>

                <div class="panel-footer panel-primary">
                  
                    <%= link_to practices_path, class: "btn btn-primary" do %>
                        <span class="glyphicon glyphicon-plus" aria-hidden="true"></span> Add Practice
                    <% end %>

                    <button type="button" class="btn btn-danger" data-action="click->patients#deletePatients">
                        <span class="glyphicon glyphicon-remove" aria-hidden="true"></span> Delete Patients
                    </button>

                    <button type="button" class="btn btn-warning" data-action="click->patients#deleteProviders">
                        <span class="glyphicon glyphicon-remove" aria-hidden="true"></span> Delete Providers
                    </button>

                    <button type="button" class="btn btn-danger" data-action="click->patients#deleteCaches">
                        <span class="glyphicon glyphicon-remove" aria-hidden="true"></span> Delete Caches
                    </button>

                    <button type="button" class="btn btn-warning" data-action="click->patients#deleteAll">
                        <span class="glyphicon glyphicon-remove" aria-hidden="true"></span> Delete All
                    </button>

                </div>
            </div>

    </div>

    <div class="col-md-12">

            <div class="panel panel-primary">

                <div class="panel-heading">
                    <h3 class="panel-title"><span class="glyphicon glyphicon-cog" aria-hidden="true"></span> Options</h3>
                </div>

                <div class="panel-body">

                    <%= form_tag("/admin/upload_patients", method: :put, multipart: true, id:"uploadForm") do %>
                        <% if !APP_CONFIG["use_opml_structure"] %>
                            <div class="form-group">
                                <%= label_tag "Choose Practice" %>
                                <%= select_tag "practice", options_for_select(@practices), include_blank: true, class: "form-control" %>
                            </div>
                        <% end %>
                        <div class="form-group">
                            <label>Choose Patient File</label>
                            <%= file_field_tag(:file) %>
                            <p class="help-block">Please upload a ZIP file.</p>
                        </div>
                </div>
                <div class="panel-footer">

                    <%= button_to "#", class: "btn btn-success", id: "uploadButton" do %>
                    <span class="glyphicon glyphicon-upload" aria-hidden="true"></span> Upload Patients
                <% end %>
                </div>
                <% end %>
            </div>
    </div>

</div>



<script>

document.addEventListener('DOMContentLoaded', function() {
    const uploadButton = document.getElementById('uploadButton');
    const uploadForm = document.getElementById('uploadForm');

    if (uploadButton && uploadForm) {
        uploadButton.addEventListener('click', function(event) {
            event.preventDefault();

            Swal.fire({
                title: 'Confirmation',
                text: 'Are you sure you want to upload patients?',
                icon: 'question',
                showCancelButton: true,
                confirmButtonColor: '#3085d6',
                cancelButtonColor: '#d33',
                confirmButtonText: 'Yes, upload patients'
            }).then((result) => {
                if (result.isConfirmed) {
                    uploadForm.submit();
                }
            });
        });
    }
});
</script>


<!--

<table class="table table-bordered">
    <caption>Actions</caption>
    <thead>
      <tr>
        <th>Action</th>
        <th>Status</th>
        <th>Options</th>
      </tr>
    </thead>
    <tbody>
    <%= form_tag("/admin/upload_patients", method: :put, multipart:"true", class:"file-upload") do%>

      <% if !APP_CONFIG["use_opml_structure"] %>
      <tr>
        <td><%= label_tag "Choose Practice" %></td>
        <td><%= select_tag "practice", options_for_select(@practices), include_blank: true, class:"form-control"%></td>	
      </tr>
      <% end %>
      <tr>
        <td>Uplodad Patient (zip file)</td>
        <td><%= file_field_tag(:file, id:"filePatient") %></td>
        <td><%= submit_tag "Upload", class:"btn btn-success btn-block" %></td>
      </tr>
    <% end %>

      <% if APP_CONFIG['use_opml_structure'] %>
        <tr>      
        <%= form_tag("/admin/upload_providers", :method => "put", :multipart=>true, :class=>"file-upload") do %>
            <td>Uplodad Providers (OPML file)</td>
            <td><%= file_field_tag(:file, id: "fileProvider")%></td>
            
        </tr>
        <% end %>
      <% end %>
    </tbody>
  </table>

    <div class="btn-patients">
        <%= button_to "Delete Patients", "/admin/remove_patients", method: :delete, class:"btn btn-danger", style:"margin-right: 5px;" %>
        <%= button_to "Delete Providers", "/admin/remove_providers", method: :delete, class:"btn btn-danger", style:"margin-right: 5px;" %>
        <%= button_to "Delete Caches", "/admin/remove_caches", method: :delete, class:"btn btn-danger", style:"margin-right: 5px;" %>
        <%= link_to "Edit Practices", practices_path, :class => "btn btn-primary" %>
    </div>

<div id="pageContent" style="padding:20px;">
<h3>Patients</h3>

  <table>

    <tr><td>patients loaded: </td>
      <td>
        <span id="patient_count"><%= @patient_count %></span> patients
        <%= image_tag "load.png", :id => "loadingPatient", 'class' => 'loader'%>
      </td>
      <td>
        <%= button_to "Delete Patients", "/admin/remove_patients", 'method' => 'delete', 'class' => 'btn btn-danger'%>
      </td>
      <td >
        
      </td>
    </tr>
    <tr><td colspan="2">&nbsp;</td></tr>

    <tr><td>cache counts: </td>
      <td>
        query cache: <%= @query_cache_count%> <br>
        patient cache: <%= @patient_cache_count%>
      </td>
      <td>
        <%= button_to "Delete Caches", "/admin/remove_caches", 'method' => 'delete', 'class' => 'btn btn-danger'%>
      </td>
    </tr>
    <tr><td colspan="2">&nbsp;</td></tr>

    <tr><td>providers loaded: </td>
      <td>
        <%= @provider_count %> providers

      </td>
      <td>
        <%= button_to "Delete Providers", "/admin/remove_providers", 'method' => 'delete', 'class' => 'btn btn-danger'%>
      </td>
    </tr>
    
    <% if !APP_CONFIG['use_opml_structure'] %>
    <tr><td colspan="2">&nbsp;</td></tr>
    <tr>
      <td> Practices </td>
      <td> <%= @practice_count %> practices </td>
      <td> <%= link_to "Edit Practices", practices_path, :class => "btn btn-large btn-success"%> </td>
    </tr>
    <% end %>

    <tr><td colspan="2">&nbsp;</td></tr>
    <%= form_tag("/admin/upload_patients", :method => "put", :multipart=>true, :class=>"file-upload") do %>
    <% if !APP_CONFIG['use_opml_structure'] %>
    <tr>
      <td> <%= label_tag "Choose practice" %> </td>
      <td> <%= select_tag "practice", options_for_select(@practices), include_blank: true, style: 'width:200px' %></td>					
    </tr>
    <% end %>
    <tr><td>Upload patient zip file: </td>
      <td>
        <%= file_field_tag(:file)%>
      </td>
      <td><%= submit_tag("Upload", 'class' => "btn btn-success") %></td>
    </tr>
    <% end %>

    <% if APP_CONFIG['use_opml_structure'] %>
      <tr><td colspan="2">&nbsp;</td></tr>
      <%= form_tag("/admin/upload_providers", :method => "put", :multipart=>true, :class=>"file-upload") do %>
      <tr><td>Upload provider opml file: </td>
        <td>
          <%= file_field_tag(:file)%>
        </td>
        <td><%= submit_tag("Upload", 'class' => "btn btn-success") %></td>
      </tr>
      <% end %>
    <% end %>

  </table>

</div>

-->
<!-- pageContent -->

<!--
<script>
  window.addEventListener("DOMContentLoaded", function(){
    $(".file-upload").submit(function(e) {
      if (this.practice.value === "") {
        alert("Please choose a practice.");
        e.preventDefault();
      }
      else if (this.file.value === "" ) {
        alert("Please provide a file.");
        this.file.focus();
        e.preventDefault();
      }
      else {
        var confs = "Are you sure you want to upload patients for the chosen practice?";
        if (confirm(confs) == false){
          e.preventDefault();
        }
      }
    });
    (function poll(){
       setTimeout(function(){
        $.getJSON( "<%= count_api_admin_patients_path %>", function(data){
          $('#patient_count').html(data.patient_count);
          //Setup the next poll recursively
          poll();
        });
      }, 5000);
    })();
  });
</script>
-->

app/views/admin/users.html.erb
<div data-controller="users" class="col-md-12">
    <div class="form-group">
        <input type="text" class="form-control" id="inputSearchUser"  placeholder="Search user..."></input>
    </div>
    <div class="panel panel-primary">
    <div class="panel-heading">
        <h3 class="panel-title"><span class="glyphicon glyphicon-user" aria-hidden="true"></span> Users</h3>
    </div>
    <div class="panel-body">
        <table class="table table-bordered">
            <thead>
                <tr>
                    <th></th>
                    <th>First Name</th>
                    <th>Last Name</th>
                    <th>Username</th>
                    <% if APP_CONFIG['use_opml_structure'] %>
                        <th>Provider</th>
                    <% else %>
                        <th>Practice</th>
                        <th>Provider</th>
                    <% end %>
                    <th>Administrator</th>
                    <th>Staff Role</th>
                    <th>Approved</th>
                    <th>Status</th>
                </tr>
            </thead>
            <% @users.each do |user| -%>
            <tbody id="userTableSearch">
                <tr>
                    <td>
                        <%= link_to(
                            content_tag(:span, '', class: 'glyphicon glyphicon-eye-open'),
                            { controller: "admin", action: "user_profile", id: user._id },
                            class: "btn btn-info"
                        ) %>

                        <%= link_to(
                            content_tag(:span, '', class: 'glyphicon glyphicon-trash'),
                            { controller: "admin", action: "delete_user", id: user._id },
                            method: 'delete',
                            class: 'btn btn-danger',
                            data: { confirm: "Are you sure you want to delete this user?" }
                        ) %>
                    </td>
                    <td><%= user.first_name %></td>
                    <td><%= user.last_name %></td>
                    <td><%= user.username %></td>
                    <% if APP_CONFIG['use_opml_structure'] %>
                        <td>
                            <select data-action="users#changeNpi" data-username="<%= user.username %>" data-name="npi" data-npi-url="<%= admin_update_npi_path %>">
                                <option value="-1">&nbsp;</option>
                                <% Provider.all.alphabetical.each do |provider| %>
                                    <option  value="<%= provider.npi %>" <%= (user.npi == provider.npi) ? "selected=\"selected\"" : ""%> ><%= provider.full_name %></option>
                                <% end %>
                            </select>
                        </td>
                    <% else %>
                        <td> 
                        <% if Provider.valid_npi?(user.npi) %>
                            N/A
                        <% else %>
                            <%= select_tag "practice", options_for_select(@practices, user.practice_id), prompt: 'None', data: { user: user.id.to_s, practiceId: user.practice_id, action: "users#changePractice", url:"set_user_practice" } %> 
                        <% end %>
                        </td>

                        <td> 
                            <% if Provider.valid_npi?(user.npi) %>
                                <% @practice_pvs = Provider.by_npi(user.npi).map {|pv| if pvtry(:parent).try(:practice) then [pv.parent.practice.name + "- " + pv.full_name, pv.id] end}%>
                                <%= select_tag "practice_provider_select", options_for_selec(@practice_pvs, user.provider_id), prompt: 'None', data:{user: user.id.to_s, providerId:user.provider_id,action:"users#changePracticeProvider", url:"set_user_practice_provider" } %> 
                            <% else %>
                                N/A
                            <% end %>
                        </td>
                    <% end %>
                    <td>
                        <% if user.admin? -%>
                            Yes - <a href="#" data-action="users#demoteUser" data-username="<%= user.username %>" data-role="admin" data-demote-url="<%= admin_demote_path %>">Revoke</a>
                        <% else -%>
                            No - <a href="#" data-action="users#promoteUser" data-username="<%= user.username %>" data-role="admin" data-promote-url="<%= admin_promote_path %>">Grant</a>
                        <% end -%>
                    </td>
                    <td>
                        <% if Provider.valid_npi?(user.npi) %>
                            N/A
                        <% else %>
                            <% if user.staff_role? -%>
                                Yes - <a href="#" data-action="users#demoteUser" data-username="<%= user.username %>" data-role="staff_role" data-demote-url="<%= admin_demote_path %>">Revoke</a>
                            <% else -%>
                                No - <a href="#" data-action="users#promoteUser" data-username="<%= user.username %>" data-role="staff_role" data-promote-url="<%= admin_promote_path %>">Grant</a>
                            <% end -%>
                        <% end %>
                    </td>
                    <td>
                        <% if user.approved? -%>
                            True
                        <% else -%>
                            <a href="#" data-action="users#approveUser" data-username="<%= user.username %>" data-approve-url="<%= admin_approve_path %>">Approve</a>
                        <% end -%>
                    </td>
                    <td>
                        <% if user.disabled? %>
                            <a href="#" data-action="users#disableOrEnableUser" data-username="<%= user.username %>" data-disable-enable-url="<%= admin_disable_path %>" data-option="0" data-action-option="Enable">Disabled</a>
                        <% else %>
                            <a href="#" data-action="users#disableOrEnableUser" data-username="<%= user.username %>" data-disable-enable-url="<%= admin_disable_path %>" data-option="1" data-action-option="Disable">Enabled</a>
                        <% end %>
                    </td>
                </tr>
            </tbody>
            <% end %>
        </table>
    </div>
    <!--
    <div class="panel-footer">
        <% if !APP_CONFIG['use_opml_structure'] %>
            <%= link_to practices_path, class: "btn btn-primary" do %>
                <span class="glyphicon glyphicon-chevron-left"></span>
                Back to Practice
            <% end %>
        <% end %>
    </div>
    -->
    </div>
</div>

<script>
    $(document).ready(function(){
        $("#inputSearchUser").on("keyup", function() {
        var value = $(this).val().toLowerCase();

    $("#userTableSearch tr").filter(function() {
        $(this).toggle($(this).text().toLowerCase().indexOf(value) > -1)
    });

  });

});
</script>