config/routes.rb
Rails.application.routes.draw do
  # Defines the root path route ("/")

  #New root: Jose Melendez
  root :to => 'dashboard#index'
  #

  #root :to => 'home#index'

  resources :providers

  #New Dashboard

  get 'dashboard(/:_id)', to: 'dashboard#index', as: 'dashboard';

  get 'dashboard/measure-result/:values', to: 'dashboard#measure_result', as: 'dashboard_measure_result'

  get 'dashboard/measure-result/patient-details/:patient_id', to: 'dashboard#patient_details', as: 'dashboard_patient_details'

  #add Jose Melendez, 10/23/2023
  resources :measures

  #
  apipie

  # devise_for :users, :controllers => {:registrations => "registrations"}
  devise_for :users, :controllers => {
    :registrations => "registrations",

    #change by Jose Melendez:
    #before:
    #:omniauth_callbacks => 'azure_auth/omniauth_callbacks'
    #after:
    :omniauth_callbacks => 'azure/omniauth_callbacks'  
    
    #:omniauth_callbacks => 'users/omniauth_callbacks' 
  }

  devise_scope :user do
    get '/users/sign_out' => 'devise/sessions#destroy' # This was neccesary, DELETE method is not working as intended
    #change by Jose Melendez:
    # get 'azure_auth/processLogin', to: 'azure_auth/omniauth_callbacks#logout_from_ad'
    get 'azure/processLogin', to: 'azure/omniauth_callbacks#logout_from_ad'

  end

  resources :practices

  resources :practices do
    collection do
      get :search
    end
  end

  get 'home/check_authorization'
  post 'home/set_reporting_period'
  
  #add Jose Melendez:
  post "dashboard/set_reporting_period"
  get "admin/users"
  post "admin/promote"
  post "admin/demote"
  post "admin/approve"
  post "admin/disable"
  post "admin/update_npi"
  get "admin/patients"
  get "admin/jobs"
  get "admin/providers"
  put "admin/upload_patients"
  put "admin/upload_providers"
  delete "admin/remove_patients"
  delete "admin/remove_caches"
  delete "admin/remove_providers"
  delete "admin/remove_all"
  delete "admin/remove_jobs"
  get "admin/user_profile"
  delete "admin/delete_user"
  post 'admin/set_user_practice'
  post 'admin/set_user_practice_provider'
  
  delete "practices/:id/remove_patients", :to => 'practices#remove_patients', as: :practices_remove_patients
  delete "practices/:id/remove_providers", :to => 'practices#remove_providers', as: :practices_remove_providers

  post "teams/:id/update", :to => 'teams#update'
  post "teams/create"
  post "teams/create_default"

  get 'teams/show_by_id/:id', to: 'teams#show_by_id', as: :show_team_by_id

  namespace :admin do

    resource :caches do
      collection do
        get :count

        #Edit Jose Melendez (descomentar)
        #get :spinner
        #get :static_measure
        #get 'static_measure/:id', :to => :static_measure
        #
      end
    end


    #Add Jose Melendez, 10/17/2023
    get "patients/patient_count", to: "patients#patient_count", defaults: { format: :json }
    

    resource :patients do
      collection do
        get :count
      end
    end
    resource :providers do
      collection do
        get :count
      end
    end
    resources :users do
      member do
        get :enable
        get :disable
        post :promote
        post :demote
        get :approve
        get :update_npi
      end
    end
  end

  resources :providers do
    resources :patients do
      collection do
        get :manage
        put :update_all
      end
    end

    get :measure_baseline

    member do
      get :merge_list
      put :merge
    end
  end

  resources :teams
  
  get "logs/index"

  namespace :api do
    
    resource :reports do
      get '*cat1.zip', :to =>'reports#cat1_zip', :format => :zip
      get 'cat1/:id/:measure_ids', :to =>'reports#cat1', :format => :xml
      get '*qrda_cat3.xml', :to =>'reports#cat3', :format => :xml
      get 'measures_spreadsheet', :to =>'reports#measures_spreadsheet'
      get 'patients', :to => 'reports#patients'
      get 'teams/team_providers/:id', :to => 'teams#team_providers'
      get 'team_report', :to => 'reports#team_report'
    end

    # The OID may contain periods, so specify a regex to allow that
    get 'value_sets/:oid', :to => 'value_sets#show', :oid => /([^\/])+?/, :format => :json

    resources :practices do
      collection do
        get :search
      end
    end

    resources :practices
    resources :teams

    resources :providers do
      collection do
        get :search
      end
      
      resources :patients do
        collection do
          get :manage
          put :update_all
        end
      end

    end

    resources :measures

    resources :queries do
      member do
       get :patients
       get :patient_results
       put :recalculate
       post :filter
       post :clearfilters
      end
    end

    namespace :admin do

      resource :caches do
        collection do
          get :count
          get :show_all
          #get :spinner REMOVE ME
          #get :static_measure REMOVE ME
          #get 'static_measure/:id', :to => :static_measure REMOVE ME
        end
      end

      resource :patients do
        collection do
          get :count
        end
      end

      resource :providers do
        collection do
          get :count
        end
      end

      resources :users do
        member do
          get :enable
          get :disable
          post :promote
          post :demote
          get :approve
          get :update_npi
        end
      end
    end
  end

  resources :patients do
    member do
      get :results
    end
  end

  namespace :api do
    resources :patients#, only: [:index, :show, :create]
  end



  # config/routes.rb


end

app/views/shared/__header.html.erb
<div class="navbar navbar-default" role="navigation">
  <div class="container">
    <div class="navbar-header col-lg-4">
      <a class="logo"  href="/" style="max-width: initial"><%= image_tag "pophealth_logo_small-trans.png" %></a>
    </div>
    <div class="collapse navbar-collapse in">
      <ul class="nav navbar-nav pull-left" style="margin-top: 10px">
        <li class="location"><%# if Provider.root %><%#= Provider.root.given_name %><%# else %><%#= APP_CONFIG['practice_name'] %><%# end %>
          <%=
            if APP_CONFIG['use_opml_structure']
              if Provider.root
                Provider.root.given_name
              else
                APP_CONFIG['practice_name']
              end
            else
              current_user.practice ? current_user.practice.name : ''
            end
          %>
        </li>
      </ul>
       <ul class="nav pull-right">
        <li class="divider-vertical"></li>
        <li class="profile">
          <div class="dropdown">
            <a class="dropdown-toggle" data-toggle="dropdown" href="#">
              <i class="glyphicon glyphicon-user"></i>
              <%= current_user.first_name.to_s %>
            </a>
            <ul class="dropdown-menu pull-right" role="menu" aria-labelledby="User">
              <% if APP_CONFIG['edit_account_enabled']%>
                <li><%=link_to raw('<i class="glyphicon glyphicon-edit"></i> Edit Account'), edit_user_registration_path(current_user) %></li>
              <% end %>
              <% if APP_CONFIG['logout_enabled']%>
                <li><%= link_to raw('<i class="glyphicon glyphicon-log-out"></i> Logout'), destroy_user_session_path, :method => :delete %></li>
              <% end %>
              <% if current_user.staff_role? || current_user.admin? %>
                <li class="divider"></li>
                <li role="presentation" class="dropdown-header">Admin</li>
                <% if current_user.admin? && !APP_CONFIG['use_opml_structure']%> 
                  <li><%= link_to raw('<i class="glyphicon glyphicon-th-large"></i> Practices'), practices_path %></li> 
                <% end %>
                <li><%= link_to raw('<i class="glyphicon glyphicon-plus"></i> Providers'), '/#providers'%></li>
                <li><%= link_to raw('<i class="glyphicon glyphicon-list"></i> Manage Teams'), '/teams'%></li>
                <% if current_user.admin? %>
                  <% if (APP_CONFIG['patient_management_enabled']) %>
                    <li><%= link_to raw('<i class="glyphicon glyphicon-eye-open"></i> Patients'), admin_patients_path%></li>
                  <% end %>
                  <% if (APP_CONFIG['job_management_enabled']) %>
                    <li><%= link_to raw('<i class="fa fa-tasks"></i> Jobs'), admin_jobs_path%></li>
                  <% end %>
                  <li><%= link_to raw('<i class="glyphicon glyphicon-user"></i> Users'), admin_users_path%></li>
                  <li><%= link_to raw('<i class="glyphicon glyphicon-list-alt"></i> Logs'), logs_index_path%></li>
                  <li><%= link_to raw('<i class="glyphicon glyphicon-plus"></i> Measures'), '/#admin/measures'%></li>
                <% end %>
              <% end %>
            </ul>
          </div>
        </li>
        <li class="divider-vertical"></li>
      </ul>
    </div>
  </div>
</div>

app/views/shared/_header.html.erb
<div class="navbar navbar-default navbar-static-top" role="navigation">
  <div class="container-fluid">

    <div class="collapse navbar-collapse in">
	<!--
      <ul class="nav navbar-nav pull-left">
        <li class="location"><%# if Provider.root %><%#= Provider.root.given_name %><%# else %><%#= APP_CONFIG['practice_name'] %><%# end %>
          <%=
            if APP_CONFIG['use_opml_structure']
              if Provider.root
                Provider.root.given_name
              else
                APP_CONFIG['practice_name']
              end
            else
              current_user.practice ? current_user.practice.name : ''
            end
          %>
        </li>
      </ul>
	  -->


      <div class="navbar-header">
        <a class="navbar-brand h1" style="margin: 0;" href="/">PopHealth</a>
      </div>

      <ul class="nav navbar-nav navbar-right">



    <form class="navbar-form navbar-left">
			<div class="form-group">
				<input type="text" class="form-control" id="search-nav" placeholder="Search..">
			</div>
			<button type="submit" class="btn btn-primary">Search</button>
		</form>


        <li class="dropdown">
            <a class="dropdown-toggle" data-toggle="dropdown" role="button" href="#" aria-haspopup="true" aria-expanded="false">
              <i class="glyphicon glyphicon-user"></i>
              <%= current_user.first_name.to_s %> <span class="caret"></span>
            </a>
            <ul class="dropdown-menu" aria-labelledby="User">
              <% if APP_CONFIG['edit_account_enabled']%>
                <li><%=link_to raw('<i class="glyphicon glyphicon-edit"></i> Edit Account'), edit_user_registration_path(current_user) %></li>
              <% end %>
              <% if APP_CONFIG['logout_enabled']%>
                <li><%= link_to raw('<i class="glyphicon glyphicon-log-out"></i> Logout'), destroy_user_session_path, :method => :delete, onclick: "localStorage.clear();"%></li>
              <% end %>
              <% if current_user.staff_role? || current_user.admin? %>
                <li role="separator" class="divider"></li>
                <li role="presentation" class="dropdown-header">Admin</li>
                <% if current_user.admin? && !APP_CONFIG['use_opml_structure']%> 
                  <li><%= link_to raw('<i class="glyphicon glyphicon-th-large"></i> Practices'), practices_path %></li> 
                <% end %>
                <!--
                <li><%= link_to raw('<i class="glyphicon glyphicon-plus"></i> Providers'), '/#providers'%></li>
                -->
                <li><%= link_to raw('<i class="glyphicon glyphicon-plus"></i> Providers'), '/providers'%></li>
                <li><%= link_to raw('<i class="glyphicon glyphicon-list"></i> Manage Teams'), '/teams'%></li>
                <% if current_user.admin? %>
                  <% if (APP_CONFIG['patient_management_enabled']) %>
                    <li><%= link_to raw('<i class="glyphicon glyphicon-eye-open"></i> Patients'), admin_patients_path%></li>
                  <% end %>
                  <% if (APP_CONFIG['job_management_enabled']) %>
                    <li><%= link_to raw('<i class="fa fa-tasks"></i> Jobs'), admin_jobs_path%></li>
                  <% end %>
                  <li><%= link_to raw('<i class="glyphicon glyphicon-user"></i> Users'), admin_users_path%></li>
                  <li><%= link_to raw('<i class="glyphicon glyphicon-list-alt"></i> Logs'), logs_index_path%></li>
                  <li><%= link_to raw('<i class="glyphicon glyphicon-plus"></i> Measures'), measures_path%></li>
                  <!--
                  <li><%= link_to raw('<i class="glyphicon glyphicon-plus"></i> Measures'), '/#admin/measures'%></li>
                  -->
                <% end %>
              <% end %>
            </ul>
        </li>
      </ul>
    </div>
  </div>
</div>

app/views/shared/_header_user.html.erb
<div class="navbar navbar-default navbar-static-top" role="navigation">
    <div class="container-fluid">
        <div class="collapse navbar-collapse in">
	        <div class="navbar-header">
                <a class="navbar-brand h1" style="margin: 0;" href="/">PopHealth</a>
            </div>
        </div>
    </div>
</div>

app/views/shared/_headers.html.erb
<div class="navbar navbar-default" role="navigation">
  <div class="container">
    <div class="navbar-header col-lg-4">
      <a class="logo"  href="/" style="max-width: initial"><%= image_tag "pophealth_logo_small-trans.png" %></a>
    </div>
    <div class="collapse navbar-collapse in">
      <ul class="nav navbar-nav pull-left" style="margin-top: 10px">
        <li class="location"><%# if Provider.root %><%#= Provider.root.given_name %><%# else %><%#= APP_CONFIG['practice_name'] %><%# end %>
          <%=
            if APP_CONFIG['use_opml_structure']
              if Provider.root
                Provider.root.given_name
              else
                APP_CONFIG['practice_name']
              end
            else
              current_user.practice ? current_user.practice.name : ''
            end
          %>
        </li>
      </ul>
       <ul class="nav pull-right">
        <li class="divider-vertical"></li>
        <li class="profile">
          <div class="dropdown">
            <a class="dropdown-toggle" data-toggle="dropdown" href="#">
              <i class="glyphicon glyphicon-user"></i>
              <%= current_user.first_name.to_s %>
            </a>
            <ul class="dropdown-menu pull-right" role="menu" aria-labelledby="User">
              <% if APP_CONFIG['edit_account_enabled']%>
                <li><%=link_to raw('<i class="glyphicon glyphicon-edit"></i> Edit Account'), edit_user_registration_path(current_user) %></li>
              <% end %>
              <% if APP_CONFIG['logout_enabled']%>
                <li><%= link_to raw('<i class="glyphicon glyphicon-log-out"></i> Logout'), destroy_user_session_path, :method => :delete %></li>
              <% end %>
              <% if current_user.staff_role? || current_user.admin? %>
                <li class="divider"></li>
                <li role="presentation" class="dropdown-header">Admin</li>
                <% if current_user.admin? && !APP_CONFIG['use_opml_structure']%> 
                  <li><%= link_to raw('<i class="glyphicon glyphicon-th-large"></i> Practices'), practices_path %></li> 
                <% end %>
                <li><%= link_to raw('<i class="glyphicon glyphicon-plus"></i> Providers'), '/#providers'%></li>
                <li><%= link_to raw('<i class="glyphicon glyphicon-list"></i> Manage Teams'), '/teams'%></li>
                <% if current_user.admin? %>
                  <% if (APP_CONFIG['patient_management_enabled']) %>
                    <li><%= link_to raw('<i class="glyphicon glyphicon-eye-open"></i> Patients'), admin_patients_path%></li>
                  <% end %>
                  <% if (APP_CONFIG['job_management_enabled']) %>
                    <li><%= link_to raw('<i class="fa fa-tasks"></i> Jobs'), admin_jobs_path%></li>
                  <% end %>
                  <li><%= link_to raw('<i class="glyphicon glyphicon-user"></i> Users'), admin_users_path%></li>
                  <li><%= link_to raw('<i class="glyphicon glyphicon-list-alt"></i> Logs'), logs_index_path%></li>
                  <li><%= link_to raw('<i class="glyphicon glyphicon-plus"></i> Measures'), '/#admin/measures'%></li>
                <% end %>
              <% end %>
            </ul>
          </div>
        </li>
        <li class="divider-vertical"></li>
      </ul>
    </div>
  </div>
</div>