config/routes.rb
Rails.application.routes.draw do
  # Defines the root path route ("/")

  #New root: Jose Melendez
  root :to => 'dashboard#index'
  #

  #root :to => 'home#index'

  resources :providers

  #New Dashboard

  get 'dashboard(/:_id)', to: 'dashboard#index', as: 'dashboard';

  get 'dashboard/measure-result/:values', to: 'dashboard#measure_result', as: 'dashboard_measure_result'

  get 'dashboard/measure-result/patient-details/:patient_id', to: 'dashboard#patient_details', as: 'dashboard_patient_details'

  #add Jose Melendez, 10/23/2023
  resources :measures

  #
  apipie

  # devise_for :users, :controllers => {:registrations => "registrations"}
  devise_for :users, :controllers => {
    :registrations => "registrations",

    #change by Jose Melendez:
    #before:
    #:omniauth_callbacks => 'azure_auth/omniauth_callbacks'
    #after:
    :omniauth_callbacks => 'azure/omniauth_callbacks'  
    
    #:omniauth_callbacks => 'users/omniauth_callbacks' 
  }

  devise_scope :user do
    get '/users/sign_out' => 'devise/sessions#destroy' # This was neccesary, DELETE method is not working as intended
    #change by Jose Melendez:
    # get 'azure_auth/processLogin', to: 'azure_auth/omniauth_callbacks#logout_from_ad'
    get 'azure/processLogin', to: 'azure/omniauth_callbacks#logout_from_ad'

  end

  resources :practices

  resources :practices do
    collection do
      get :search
    end
  end

  get 'home/check_authorization'
  post 'home/set_reporting_period'
  
  #add Jose Melendez:
  post "dashboard/set_reporting_period"
  get "admin/users"
  post "admin/promote"
  post "admin/demote"
  post "admin/approve"
  post "admin/disable"
  post "admin/update_npi"
  get "admin/patients"
  get "admin/jobs"
  get "admin/providers"
  put "admin/upload_patients"
  put "admin/upload_providers"
  delete "admin/remove_patients"
  delete "admin/remove_caches"
  delete "admin/remove_providers"
  delete "admin/remove_all"
  delete "admin/remove_jobs"
  get "admin/user_profile"
  delete "admin/delete_user"
  post 'admin/set_user_practice'
  post 'admin/set_user_practice_provider'
  
  delete "practices/:id/remove_patients", :to => 'practices#remove_patients', as: :practices_remove_patients
  delete "practices/:id/remove_providers", :to => 'practices#remove_providers', as: :practices_remove_providers

  post "teams/:id/update", :to => 'teams#update'
  post "teams/create"
  post "teams/create_default"

  get 'teams/show_by_id/:id', to: 'teams#show_by_id', as: :show_team_by_id

  namespace :admin do

    resource :caches do
      collection do
        get :count

        #Edit Jose Melendez (descomentar)
        #get :spinner
        #get :static_measure
        #get 'static_measure/:id', :to => :static_measure
        #
      end
    end


    #Add Jose Melendez, 10/17/2023
    get "patients/patient_count", to: "patients#patient_count", defaults: { format: :json }
    

    resource :patients do
      collection do
        get :count
      end
    end
    resource :providers do
      collection do
        get :count
      end
    end
    resources :users do
      member do
        get :enable
        get :disable
        post :promote
        post :demote
        get :approve
        get :update_npi
      end
    end
  end

  resources :providers do
    resources :patients do
      collection do
        get :manage
        put :update_all
      end
    end

    get :measure_baseline

    member do
      get :merge_list
      put :merge
    end
  end

  resources :teams
  
  get "logs/index"

  namespace :api do
    
    resource :reports do
      get '*cat1.zip', :to =>'reports#cat1_zip', :format => :zip
      get 'cat1/:id/:measure_ids', :to =>'reports#cat1', :format => :xml
      get '*qrda_cat3.xml', :to =>'reports#cat3', :format => :xml
      get 'measures_spreadsheet', :to =>'reports#measures_spreadsheet'
      get 'patients', :to => 'reports#patients'
      get 'teams/team_providers/:id', :to => 'teams#team_providers'
      get 'team_report', :to => 'reports#team_report'
    end

    # The OID may contain periods, so specify a regex to allow that
    get 'value_sets/:oid', :to => 'value_sets#show', :oid => /([^\/])+?/, :format => :json

    resources :practices do
      collection do
        get :search
      end
    end

    resources :practices
    resources :teams

    resources :providers do
      collection do
        get :search
      end
      
      resources :patients do
        collection do
          get :manage
          put :update_all
        end
      end

    end

    resources :measures

    resources :queries do
      member do
       get :patients
       get :patient_results
       put :recalculate
       post :filter
       post :clearfilters
      end
    end

    namespace :admin do

      resource :caches do
        collection do
          get :count
          get :show_all
          #get :spinner REMOVE ME
          #get :static_measure REMOVE ME
          #get 'static_measure/:id', :to => :static_measure REMOVE ME
        end
      end

      resource :patients do
        collection do
          get :count
        end
      end

      resource :providers do
        collection do
          get :count
        end
      end

      resources :users do
        member do
          get :enable
          get :disable
          post :promote
          post :demote
          get :approve
          get :update_npi
        end
      end
    end
  end

  resources :patients do
    member do
      get :results
    end
  end

  namespace :api do
    resources :patients#, only: [:index, :show, :create]
  end



  # config/routes.rb


end

app/controllers/practices_controller.rb
class PracticesController < ApplicationController
  #add Jose Melendez, 05/12/2023
  before_action :set_practice, only: [:edit, :update, :destroy]
  include LogsHelper 
  include ApplicationHelper

  authorize_resource
  before_action :authenticate_user!  
 	before_action :validate_authorization

  # GET /practice
  # GET /practice.json
  
  def validate_authorization
  	authorize! :admin, :practice
  end
  
  def index
    log_call LogAction::SEARCH, "Practices Controller - List practices"

    @practices = Practice.all
    #Add Jose Melendez: Create a variable that counts the practices that have an associated provider_id
    @practices_with_provider = Practice.where(:provider_id.ne => nil).count
    #
		@practice = Practice.new
		@users = User.all.map {|user| [user.username, user.id]}
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @practice }
    end
  end

  # GET /practices/1
  # GET /practices/1.json
  def show
    @practice = Practice.find(params[:id])
    @users = User.all.map {|user| [user.username, user.id]}

    if @practice.nil?
      respond_to do |format|
        format.html { redirect_to practices_path, notice: 'A practice with that identifier could not be found.' }
        format.json { render json: @practice, status: :not_found }
      end
    else
      log_call LogAction::READ, "Practices Controller - View practice"

      respond_to do |format|
        format.html # index.html.erb
        format.json { render json: @practice }
      end
    end
  end
  
  # POST /practices
  # POST /practices.json
  def create
    log_call LogAction::CREATE, "Practices Controller - Create new practice"
  begin
    @practice = Practice.new(name: params[:practice]['name'], organization: params[:practice]['organization'], address: params[:practice]['address'])
    @practice.save
    if @practice.save
      identifier = CDAIdentifier.new(:root => "Organization", :extension => @practice.organization)
      provider = Provider.new(:given_name => @practice.name)
      provider.cda_identifiers << identifier
      #TODO
      # provider.parent = Provider.root
      provider.save
      @practice.provider = provider
      if params[:user] != ''
        user = User.find(params[:user])
        @practice.users << user
        user.save
      end
    end
    respond_to do |format|
      if @practice.save
        format.html { redirect_to practices_path, notice: 'Practice was successfully created.' }
        format.json { render json: @practice, status: :created, location: @practice }
      else
        format.html { redirect_to practices_path }
        format.json { render json: @practice.errors, status: :unprocessable_entity }
      end
    end
  rescue Exception => e
    puts "Error creating practice"
    puts e.message
  end
  end

  # PUT /practices
  # PUT /practices.json

  #Modify by Jose Melendez, 05/12/2023
  def update
    @practice = Practice.find(params[:id])

    if @practice
      log_call LogAction::UPDATE, "Practices Controller - Practices Controller - Update practice"

      if @practice.update(practice_params)
        respond_to do |format|
          format.html { redirect_to practices_path, notice: 'Practice was successfully updated.' }
          format.json { render json: @practice, status: :created, location: @practice }
        end
      else
        respond_to do |format|
          format.html { redirect_to practices_path }
          format.json { render json: @practice.errors, status: :unprocessable_entity }
        end
      end
    else
    end
  end


  # def update
  #   @practice = Practice.find(params[:id])
  #   @practice.update_attributes(params[:practice]) unless @practice.nil?

  #   respond_to do |format|
  #     if @practice.save
  #       log_controller_call LogAction::UPDATE, "Update practice"
  #       format.html { redirect_to practices_path, notice: 'Practice was successfully updated.' }
  #       format.json { render json: @practice, status: :created, location: @practice }
  #     else
  #       log_controller_call LogAction::UPDATE, "Failed to update practice, with errors #{get_errors_for_log(@practice)}"
  #       format.html { redirect_to practices_path }
  #       format.json { render json: @practice.errors, status: :unprocessable_entity }
  #     end
  #   end
  # end

  def remove_patients
    @practice = Practice.find(params[:id])

    if(@practice)
      log_call LogAction::DELETE, "Practices Controller - Remove all patients from practice"

      remove_patients_from_practice(params[:id]) #see ApplicationHelper module 
      respond_to do |format|
        format.html { redirect_to :action => :index }
      end
    else
      format.html { redirect_to practices_path }
      format.json { render json: @practice.errors, status: :unprocessable_entity }
    end

  end
  
  def remove_providers
    @practice = Practice.find(params[:id])

    if(@practice)
      log_call LogAction::DELETE, "Practices Controller - Remove all providers from practice"

      Provider.where(parent_id: practice.provider.id).delete
    
      respond_to do |format|
        format.html { redirect_to :action => :index }
      end
    else
      format.html { redirect_to practices_path }
      format.json { render json: @practice.errors, status: :unprocessable_entity }
    end

  end
  
  # DELETE /practices/1
  # DELETE /practices/1.json
  def destroy
    @practice = Practice.find(params[:id])

    if(@practice)
      log_call LogAction::DELETE, "Practices Controller - Delete practice"
      
      if @practice.provider
        id = @practice.provider.id

        @current_user.teams.each do |tm|
          tm.providers.delete(id.to_s)
          tm.save!
        end

        @current_user.save!
        @practice.provider.delete
      end

      @practice.destroy
  
      respond_to do |format|
        format.html { redirect_to :action => :index}
      end
    else
      format.html { redirect_to practices_path }
      format.json { render json: @practice.errors, status: :unprocessable_entity }
    end

  end

private

def practice_params
  params.require(:practice).permit('name', 'organization', 'address')
end

#add Jose Melendez, 05/12/2023
def set_practice
  log_call LogAction::READ, "Practices Controller - View practice"

  @practice = Practice.find(params[:id])
end

end

app/views/practices/___edit_practice.html.erb
<div class='form-inline'>
<%= form_for @practice do |f| %>
  <% if @practice.errors.any? %>
	<div id="error_explanation">
	  <h2><%= pluralize(@practice.errors.count, "error") %> prohibited this practice from being saved:</h2>
	  <ul>
	  <% @practice.errors.full_messages.each do |msg| %>
		<li><%= msg %></li>
	  <% end %>
	  </ul>
	</div>
  <% end %>

  <h4> <%= @practice.new_record? ? "Create" : "Edit" %> Practice </h4>
  <table class="table-condensed table-hover">
	<tbody>
	  <tr>
		<td><%= f.label :name, "*Name" %></td>
		<td><%= f.text_field :name %></td>        
	  </tr>
	  <tr>
		<td><%= f.label :organization, "*Organization" %></td>
		<td><%= f.text_field :organization %></td>        
	  </tr>
	  <tr>
		<td><%= f.label :address %></td>
		<td><%= f.text_area :address %></td>        
	  </tr>
	  <% if @practice.new_record? %>
	  <tr>
		<td><%= f.label :user, "User" %></td>
		<td><%= select_tag :user, options_for_select(@users), include_blank: true %></td>        
	  </tr>
	  <% end %>
	  <tr class='pull-right'> <td><%= f.submit class: "btn new-practice-btn"%></td> </tr>
	</tbody>
  </table>

<% end %>
</div>

app/views/practices/___index.html.erb
<!--
<div class="practices">
  <h1>Practices</h1>
  <br/>  
  <%= render 'edit_practice' %>
	<br />
	<h4> Current Practices </h4>
	<table class="table">
    <thead>
      <tr>
        <th>Name</th>
        <th>Organization</th>
        <th>Address</th>
        <th>User(s)</th>
        <th>Patients</th>
        <th>Providers</th>
        <th></th>
        <th></th>
        <th></th>
        <th></th>
      </tr>
    </thead>
  <% @practices.each do |practice| %>
    <tbody>
      <tr>
        <td><%= practice.name %></td>
        <td><%= practice.organization %></td>
        <td><%= practice.address %></td> 
        <td><%= practice.users ? practice.users.map {|u| u.username}.join(", ") : 'N/A' %></td>                
        <td><%= practice.cqmPatient ? practice.cqmPatient.count : 0 %></td>
        <td><%= practice.provider ? practice.provider.descendants.count : 'N/A'%></td>
        <td><%= link_to "Edit Practice", practice_path(practice.id), :class => "btn btn-primary" %></td>
        <td><%= link_to "Delete Providers", practices_remove_providers_path(id: practice.id), method: :delete, data: { confirm: 'Are you sure you want to delete all providers for ' + "#{practice.name}?"} %></td>
        <td><%= link_to "Delete Patients", practices_remove_patients_path(id: practice.id), method: :delete, data: { confirm: 'Are you sure you want to delete all patients for ' + "#{practice.name}?"} %></td>
        <td><%= link_to 'Delete Practice', practice, method: :delete, data: { confirm: 'Are you sure? There may be patients tied to this practice' } %></td>
      </tr>
    </tbody>
  <% end %>
  </table>
	<br />
  <%= link_to 'Back to Users', "/admin/users", class: 'btn btn-success' %>
  <%= link_to 'Back to Patients', "/admin/patients", class: 'btn btn-info' %>
</div>

-->

app/views/practices/edit.html.erb
<div data-controller="practices" class="col-md-12">
    <div class="panel panel-primary">

        <div class="panel-heading">
            <h3 class="panel-title"><span class="glyphicon glyphicon-user" aria-hidden="true"></span> Edit Practice: <%= @practice.name  %></h3>
            <% if @practice.errors.any? %>
                <div>
                    <h2><%= pluralize(@practice.errors.count, "error") %> prohibited this practice from being saved:</h2>
                    <ul>
                        <% @practice.errors.full_messages.each do |msg| %>
                            <li><%= msg %></li>
                        <% end %>
                    </ul>
                </div>
            <% end %>
        </div>
        <div class="panel-body">

            <%= form_for @practice do |f| %>
            
                <div class="form-group">
                    <%= f.label :name, "Name" %>
                    <%= f.text_field :name, class:"form-control" %>
                </div>
                <div class="form-group">
                    <%= f.label :organization, "Organization" %>
                    <%= f.text_field :organization, class:"form-control"%>
                </div>
                <div class="form-group">
                    <%= f.label :address %>
                    <%= f.text_area :address, class:"form-control", style: "resize: vertical;"%>
                </div>
                <% if @practice.new_record? %>
                    <div class="form-group">
                        <%= f.label :user, "User" %>
                        <%= select_tag :user, options_for_select(@users), include_blank: true, class:"form-control" %>        
                    </div>
                <% end %>
            
        </div>
        <div class="panel-footer panel-primary">
            <!--<%= f.submit class: "btn btn-primary" %>-->
            <%= link_to '/practices', class: 'btn btn-primary' do %>
                <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span> Back to List
            <% end %>
            <%= f.button type: "submit", class: "btn btn-success" do %>
                <span class="glyphicon glyphicon-save" aria-hidden="true"></span> Save
            <% end %>
        </div>

        <% end %>
    </div>
</div>

app/views/practices/index.html.erb
<div data-controller="practices" class="col-md-12">
    <div class="form-group">
        <input type="text" class="form-control" id="inputSearchPractice"  placeholder="Search practice..."></input>
    </div>
    <div class="panel panel-primary" class="col-md-12">
        <div>
            <input type="text" class="form-control" id="inputSearchMeasure"  placeholder="Search measure..."></input>
        </div>

        <div class="panel-heading" id="headingTeams">
            <h3 class="panel-title"><span class="glyphicon glyphicon-paperclip" aria-hidden="true"></span> Current Practices</h3>
        </div>

        <div class="panel-body">
            <table class="table table-bordered">
                <thead>
                    <tr>
                        <th style="width:5%;"></th>
                        <th>Name</th>
                        <th>Organization</th>
                        <th>Address</th>
                        <th>User(s)</th>
                        <th>Patients</th>
                        <th>Providers</th>
                        <th style="width:10%;">Actions</th>
                    </tr>
                </thead>
                <tbody id="practiceTable">
                    <% @practices.each do |practice| %>
                    <tr>
                        <td>
                            <div class="btn-teams-options">
                                <%= link_to edit_practice_path(practice.id), class: "btn btn-primary btn-sm" do %>
                                    <span class="glyphicon glyphicon-pencil" aria-hidden="true"></span>
                                <% end %>
                                <%= link_to practice, method: :delete, data: { confirm: 'Are you sure? There may be patients tied to this practice' }, class: "btn btn-danger btn-sm" do %>
                                    <span class="glyphicon glyphicon-trash" aria-hidden="true"></span>
                                <% end %>
                            </div>
                        </td>
                        <td><%= practice.name %></td>
                        <td><%= practice.organization %></td>
                        <td><%= practice.address %></td>
                        <td><%= practice.users ? practice.users.map {|u| u.username}.join(", ") : 'N/A' %></td>
                        <td><%= practice.cqmPatient ? practice.cqmPatient.count : 0 %></td>
                        <!--<td><%= practice.providers ? practice.providers.descendants.count : 0 %></td>-->
                        <td><%= @practices_with_provider %></td>
                        
                        <td>
                            <div class="btn-teams-options">
                                <%= link_to practices_remove_providers_path(id: practice.id), method: :delete, data: { confirm: 'Are you sure you want to delete all providers for ' + "#{practice.name}?"}, class: "btn btn-warning" do %>
                                    <span class="glyphicon glyphicon-remove" aria-hidden="true"></span> Delete Providers
                                <% end %>

                                <%= link_to practices_remove_patients_path(id: practice.id), method: :delete, data: { confirm: 'Are you sure you want to delete all patients for ' + "#{practice.name}?"}, class: "btn btn-danger" do %>
                                    <span class="glyphicon glyphicon-remove" aria-hidden="true"></span> Delete Patients
                                <% end %>
                            </div>
                        </td>
                    </tr>
                    <% end %>
                </tbody>
            </table>
        </div>
        <div class="panel-footer panel-primary">

            <!--
            <%= link_to '/admin/users', class: 'btn btn-primary' do %>
                <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span> Back to Users
            <% end %>
            -->

            <%= link_to '/admin/patients', class: 'btn btn-primary' do %>
                <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span> Back to Patients
            <% end %>

            <button data-toggle="modal" data-target="#newPracticeModal" class="btn btn-success"><span class="glyphicon glyphicon-plus" aria-hidden="true"></span> New</button>



        </div>
    </div>

    <!-- Create Practice Modal -->

    <div class="modal fade" id="newPracticeModal" role="dialog" aria-labelledby="newPracticeModal">
    
        <div class="modal-dialog" role="document">
        
            <div class="modal-content">
            
                <div class="modal-header">

                    <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                    
                    <h4 class="modal-title" id="newPracticeModalLabel">Create New Practice</h4>
                
                </div>

                <%= form_for @practice do |f| %>
                    <div class="modal-body">

                    <% if @practice.errors.any? %>

                            <div id="error_explanation">
                            
                                <h2><%= pluralize(@practice.errors.count, "error") %> prohibited this practice from being saved:</h2>

                                <ul>
                                    <% @practice.errors.full_messages.each do |msg| %>

                                        <li><%= msg %></li>
                                    <% end %>
                                </ul>
                            </div>

                    <% end %>

                    <div class="form-group">
                        <label for="practiceId">Name</label>
                        <%= f.text_field :name, class:"form-control", id:"practiceId", required: true%>
                    </div>

                    <div class="form-group">
                            <label for="organizationPractice">Organization</label>
                            <%= f.text_field :organization, class:"form-control", id:"organizationPractice", required: true %>
                    </div>

                    <div class="form-group">
                        <label for="addressPractice">Address</label>
                        <%= f.text_area :address, class:"form-control",id:"addressPractice" %>
                    </div>

                    <% if @practice.new_record? %>
                        <div class="form-group">
                            <label for="userPractice">User</label>
                            <%= select_tag :user, options_for_select(@users), include_blank: true,class:"form-control", id:"userPractice" %>
                        </div>
                    <% end %>

                    </div>

                    <div class="modal-footer">

                        <%= f.submit "Save", class:"btn btn-success pull-left" %>

                    </div>
                <% end %>
            </div>
        </div>
    
    </div>

</div>

<script>

    $(document).ready(function(){
        $("#inputSearchPractice").on("keyup", function() {
        var value = $(this).val().toLowerCase();

    $("#practiceTable tr").filter(function() {
        $(this).toggle($(this).text().toLowerCase().indexOf(value) > -1)
    });

  });

});
</script>

app/views/practices/show.html.erb
<div class="practices">
  <h1>Practices</h1>
  <br/>  
  <%= render 'edit_practice' %>
  <br />
  <%= link_to 'Back to Practices', practices_path, class: 'btn btn-success' %>
</div>