config/routes.rb
Rails.application.routes.draw do
  # Defines the root path route ("/")

  #New root: Jose Melendez
  root :to => 'dashboard#index'
  #

  #root :to => 'home#index'

  resources :providers

  #New Dashboard

  get 'dashboard(/:_id)', to: 'dashboard#index', as: 'dashboard';

  get 'dashboard/measure-result/:values', to: 'dashboard#measure_result', as: 'dashboard_measure_result'

  get 'dashboard/measure-result/patient-details/:patient_id', to: 'dashboard#patient_details', as: 'dashboard_patient_details'

  #add Jose Melendez, 10/23/2023
  resources :measures

  #
  apipie

  # devise_for :users, :controllers => {:registrations => "registrations"}
  devise_for :users, :controllers => {
    :registrations => "registrations",

    #change by Jose Melendez:
    #before:
    #:omniauth_callbacks => 'azure_auth/omniauth_callbacks'
    #after:
    :omniauth_callbacks => 'azure/omniauth_callbacks'  
    
    #:omniauth_callbacks => 'users/omniauth_callbacks' 
  }

  devise_scope :user do
    get '/users/sign_out' => 'devise/sessions#destroy' # This was neccesary, DELETE method is not working as intended
    #change by Jose Melendez:
    # get 'azure_auth/processLogin', to: 'azure_auth/omniauth_callbacks#logout_from_ad'
    get 'azure/processLogin', to: 'azure/omniauth_callbacks#logout_from_ad'

  end

  resources :practices

  resources :practices do
    collection do
      get :search
    end
  end

  get 'home/check_authorization'
  post 'home/set_reporting_period'
  
  #add Jose Melendez:
  post "dashboard/set_reporting_period"
  get "admin/users"
  post "admin/promote"
  post "admin/demote"
  post "admin/approve"
  post "admin/disable"
  post "admin/update_npi"
  get "admin/patients"
  get "admin/jobs"
  get "admin/providers"
  put "admin/upload_patients"
  put "admin/upload_providers"
  delete "admin/remove_patients"
  delete "admin/remove_caches"
  delete "admin/remove_providers"
  delete "admin/remove_all"
  delete "admin/remove_jobs"
  get "admin/user_profile"
  delete "admin/delete_user"
  post 'admin/set_user_practice'
  post 'admin/set_user_practice_provider'
  
  delete "practices/:id/remove_patients", :to => 'practices#remove_patients', as: :practices_remove_patients
  delete "practices/:id/remove_providers", :to => 'practices#remove_providers', as: :practices_remove_providers

  post "teams/:id/update", :to => 'teams#update'
  post "teams/create"
  post "teams/create_default"

  get 'teams/show_by_id/:id', to: 'teams#show_by_id', as: :show_team_by_id

  namespace :admin do

    resource :caches do
      collection do
        get :count

        #Edit Jose Melendez (descomentar)
        #get :spinner
        #get :static_measure
        #get 'static_measure/:id', :to => :static_measure
        #
      end
    end


    #Add Jose Melendez, 10/17/2023
    get "patients/patient_count", to: "patients#patient_count", defaults: { format: :json }
    

    resource :patients do
      collection do
        get :count
      end
    end
    resource :providers do
      collection do
        get :count
      end
    end
    resources :users do
      member do
        get :enable
        get :disable
        post :promote
        post :demote
        get :approve
        get :update_npi
      end
    end
  end

  resources :providers do
    resources :patients do
      collection do
        get :manage
        put :update_all
      end
    end

    get :measure_baseline

    member do
      get :merge_list
      put :merge
    end
  end

  resources :teams
  
  get "logs/index"

  namespace :api do
    
    resource :reports do
      get '*cat1.zip', :to =>'reports#cat1_zip', :format => :zip
      get 'cat1/:id/:measure_ids', :to =>'reports#cat1', :format => :xml
      get '*qrda_cat3.xml', :to =>'reports#cat3', :format => :xml
      get 'measures_spreadsheet', :to =>'reports#measures_spreadsheet'
      get 'patients', :to => 'reports#patients'
      get 'teams/team_providers/:id', :to => 'teams#team_providers'
      get 'team_report', :to => 'reports#team_report'
    end

    # The OID may contain periods, so specify a regex to allow that
    get 'value_sets/:oid', :to => 'value_sets#show', :oid => /([^\/])+?/, :format => :json

    resources :practices do
      collection do
        get :search
      end
    end

    resources :practices
    resources :teams

    resources :providers do
      collection do
        get :search
      end
      
      resources :patients do
        collection do
          get :manage
          put :update_all
        end
      end

    end

    resources :measures

    resources :queries do
      member do
       get :patients
       get :patient_results
       put :recalculate
       post :filter
       post :clearfilters
      end
    end

    namespace :admin do

      resource :caches do
        collection do
          get :count
          get :show_all
          #get :spinner REMOVE ME
          #get :static_measure REMOVE ME
          #get 'static_measure/:id', :to => :static_measure REMOVE ME
        end
      end

      resource :patients do
        collection do
          get :count
        end
      end

      resource :providers do
        collection do
          get :count
        end
      end

      resources :users do
        member do
          get :enable
          get :disable
          post :promote
          post :demote
          get :approve
          get :update_npi
        end
      end
    end
  end

  resources :patients do
    member do
      get :results
    end
  end

  namespace :api do
    resources :patients#, only: [:index, :show, :create]
  end



  # config/routes.rb


end

app/controllers/api/measures_controller.rb
require 'measure/loader.rb'
require 'cql_bundle_importer.rb'
require './contrib/measure_dates.rb'
require './app/models/tracker.rb'

module Api

  class LightMeasureSerializer

    include ActiveModel::Serialization  

        attr_accessor :_id, :name, :category, :hqmf_id, :type, :cms_id, :nqf_id, :hqmf_set_id, :hqmf_version_number, :sub_id, :subtitle, :description

  end
  
  class MeasuresController < ApplicationController

    resource_description do
      short 'Measures'
      formats ['json']
      description "This resource allows for the management of clinical quality measures in the popHealth application."
    end

    include PaginationHelper

    include LogsHelper

    before_action :authenticate_user!
    before_action :validate_authorization!
    before_action :set_pagination_params, :only=> :index
    before_action :create_filter , :only => :index
    before_action :update_metadata_params, :only => :update_metadata
    
    
    #api :GET, "/measureslight", "Get a list of measures light"
    param_group :pagination, Api::PatientsController

    def measureslight

      #log_api_call LogAction::READ, "View list of measures"
      
      measures = Measure.where(@filter)
 
      measLight = Array.new

      measures.each do |item|

        p = LightMeasureSerializer.new
        p._id = item._id
        p.name = item.title
        p.category = item.category 
        p.hqmf_id = item.hqmf_id
        p.type = item.reporting_program_type
        p.cms_id = item.cms_id
        p.nqf_id = nil if item[:nqf_id]
        p.hqmf_set_id = item.hqmf_set_id
        p.hqmf_version_number = item.hqmf_version_number
        p.sub_id = nil if item[:sub_id]
        p.subtitle = nil if item[:subtitle]
        p.description = item.description

        measLight << p

      end
     
       render json: measLight

    end

    api :GET, "/measures", "Get a list of measures"

    param_group :pagination, Api::PatientsController
    
    def index

      log_call LogAction::SEARCH, "API Measures Controller - List measures"

      measures = Measure.where(@filter)
      #m = Measure.first
      #Delayed::Worker.logger.info("************** what is M **************")
      #Delayed::Worker.logger.info(m)
      render json: measures
      #paginate(api_measures_url, measures), each_serializer: HealthDataStandards::CQM::MeasureSerializer

    end

    api :GET, "/measures/:id", "Get an individual clinical quality measure"
    param :id, String, :desc => 'The HQMF id for the CQM to calculate', :required => true
    param :sub_id, String, :desc => 'The sub id for the CQM to calculate. This is popHealth specific.', :required => false

    def show
      
      log_call LogAction::READ, "API Measures Controller - View measures"
      
      measure = Measure.where({"hqmf_id" => params[:id]}).first
      render :json => measure
    end

    api :POST, "/measures", "Load a measure into popHealth"
    description "The uploaded measure must be in the popHealth JSON measure format. This will not accept HQMF definitions of measures."
    def create
      authorize! :create, Measure
      bundle_file = File.new(params[:measure_file].tempfile.path)
      importer = CqlBundle::CqlBundleImporter
      @bundle = importer.import(bundle_file, Tracker.new, false)
      # Added by yockler (We can now import bundles using this)
=begin
      measure_details = {
        'type'=>params[:measure_type],
        'episode_of_care'=>params[:calculation_type] == 'episode',
        'category'=> params[:category].empty? ?  "miscellaneous" : params[:category],
        'lower_is_better'=> params[:lower_is_better]
      }
      ret_value = {}
      hqmf_document = Measures::Loader.parse_model(params[:measure_file].tempfile.path)
      if measure_details["episode_of_care"]
        Measures::Loader.save_for_finalization(hqmf_document)
        ret_value= {episode_ids: hqmf_document.specific_occurrence_source_data_criteria().collect{|dc| {id: dc.id, description: dc.description}},
                    hqmf_id: hqmf_document.hqmf_id,
                    vsac_username: params[:vsac_username],
                    vsac_password: params[:vsac_password],
                    category: measure_details["category"],
                    lower_is_better: measure_details[:lower_is_better],
                    hqmf_document: hqmf_document
                  }
      else
        Measures::Loader.generate_measures(hqmf_document,params[:vsac_username],params[:vsac_password],measure_details)
      end
      #log_api_call LogAction::UPDATE, "Loaded measure"
      render json: ret_value
=end
      rescue => e
        #log_api_call LogAction::UPDATE, "Failed to load measure, with error #{e}"
        render text: e.to_s, status: 500
    end

    api :DELETE, '/measures/:id', "Remove a clinical quality measure from popHealth"
    param :id, String, :desc => 'The HQMF id for the CQM to calculate', :required => true
    description "Removes the measure from popHealth. It also removes any calculations for that measure."
    def destroy
      authorize! :delete, Measure
      measure = Measure.where({"hqmf_id" => params[:id]})

      if(measure)
        log_call LogAction::DELETE, "API Measures Controller - Delete measure"

        #delete all of the pateint and query cache entries for the measure
        #HealthDataStandards::CQM::PatientCache.where({"value.measure_id" => params[:id]}).destroy
        #HealthDataStandards::CQM::QueryCache.where({"measure_id" => params[:id]}).destroy
        measure.destroy
        render :status=>204, :text=>""
      else
        render :status=>404, :text=>"Not found"
      end

    end

    def update_metadata
      authorize! :update, Measure

      measures = Measure.where({ hqmf_id: params[:hqmf_id]})

      log_call LogAction::UPDATE, "API Measures Controller - Update measures metadata"

      measures.each do |m|
        m.update_attributes(params[:measure])
        m.save
      end

      render json:  measures,  each_serializer: HealthDataStandards::CQM::MeasureSerializer
      rescue => e
        render text: e.to_s, status: 500
    end

    def finalize

      measure_details = {
          'episode_ids'=>params[:episode_ids],
          'category' => params[:category],
          'measure_type' => params[:measure_type],
          'lower_is_better' => params[:lower_is_better]

       }

      Measures::Loader.finalize_measure(params[:hqmf_id],params[:vsac_username],params[:vsac_password],measure_details)

      measure = Measure.where({hqmf_id: params[:hqmf_id]}).first

      if(measure)
        log_call LogAction::UPDATE, "API Measures Controller - Finalize measure"

        render json: measure, serializer: HealthDataStandards::CQM::MeasureSerializer
      else
        render text: "Measure not found", status: 404
      end

      rescue => e
        render text: e.to_s, status: 500
      end
    end

  private

    def validate_authorization!
      authorize! :read, Measure
    end

    def create_filter
      measure_ids = params[:measure_ids]
      @filter = measure_ids.nil? || measure_ids.empty? ? {} : {:hqmf_id.in => measure_ids}
    end

    def update
      params[:measure][:lower_is_better] = nil if params[:measure][:lower_is_better].blank?
    end

  end
end

app/controllers/measures_controller.rb
class MeasuresController < ApplicationController

    require 'will_paginate/mongoid'

    Model = CQM::Measure

    def index

        @measures = Model.all.paginate(page: params[:page], per_page: 5)

    end

    def edit

        @measure = Model.find(params[:id])

    end

    def update

        @measure = Model.find(params[:id])

        if @measure.update(measure_params)

            flash[:notice] = "Measure Updated Successfully"

            redirect_to edit_measure_path(@measure)

        else

            render :edit

        end

    end


    private

    def measure_params

        params.require(:cqm_measure).permit(:description)

    end

end

app/helpers/measures_helper.rb
module MeasuresHelper
end

app/views/measures/_edit_measure.html.erb
<div data-controller="measures">
    <% if @measure.present? %>
        <%= form_for @measure, url: measure_path(@measure), method: :patch do |f| %>
        <div class="form-group">
            <%= f.label :description, "Description" %>
            <%= f.text_field :description, class: "form-control" %>
        </div>
            <%= f.submit "Update" %>
        <% end %>

        <% if flash[:notice].present? %>
            <div class="alert alert-success">
                <%= flash[:notice] %>
            </div>
        <% end %>
    <% end %>
    <h1>Hello</h1>
</div>

app/views/measures/edit.html.erb
<div data-controller="measures" class="col-md-12">
    <div class="panel panel-primary">
        <div class="panel-heading">
            <h3 class="panel-title"><span class="glyphicon glyphicon-user" aria-hidden="true"></span>Edit Measure: <%= @measure.title %></h3>
        </div>
        <div class="panel-body">
            <%= form_for @measure, url: measure_path(@measure), method: :patch do |f| %>
                <div class="form-group">
                    <%= f.label :description, "Description" %>
                    <%= f.text_field :description, class: "form-control" %>
                </div>
        </div>
        <div class="panel-footer panel-primary">
            <%= f.submit 'Save', class: "btn btn-success" %>
            <%= link_to measures_path, class: "btn btn-primary" do %>
                <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span> Back to List
            <% end %>
            <% end %>
            <% if flash[:notice].present? %>
                <div class="alert alert-success">
                    <%= flash[:notice] %>
                </div>
            <% end %>
        </div>
    </div>
</div>

app/views/measures/index.html.erb
<div data-controller="measures" class="col-md-12">

    <div class="form-group">
        <input type="text" class="form-control" id="inputSearchMeasure"  placeholder="Search measure..."></input>
    </div>
    <div class="panel panel-primary">

        <div class="panel-heading">
            <h3 class="panel-title"><span class="glyphicon glyphicon-stats" aria-hidden="true"></span> Measures</h3>
        </div>

        <div class="panel-body">
            <table class="table table-bordered table-hover">
                <thead>
                    <tr>
                        <th></th>
                        <th>CMS ID</th>
                        <th>HQMF ID</th>
                        <th>Name</th>
                        <th>Description</th>
                    </tr>
                </thead>
                <tbody id="measureTableSearch">
                    <% @measures.each do |measure| %>
                        <tr>
                            <td><%= link_to edit_measure_path(measure), class: "btn btn-primary btn-sm" do %>
                                <span class="glyphicon glyphicon-pencil" aria-hidden="true"></span>
                                <% end %>
                            </td>
                            <td><%= measure.cms_id %></td>
                            <td><%= measure.hqmf_id %></td>
                            <td><%= measure.title %></td>
                            <td><%= measure.description %></td>
                        </tr>
                    <% end %>
                </tbody>
            </table>
        </div>

        <div class="panel-footer panel-primary">
            <%= will_paginate @measures, class:"pager" %>
        </div>
    
    </div>

    
</div>

<script>

    $(document).ready(function(){
        $("#inputSearchMeasure").on("keyup", function() {
        var value = $(this).val().toLowerCase();

    $("#measureTableSearch tr").filter(function() {
        $(this).toggle($(this).text().toLowerCase().indexOf(value) > -1)
    });

  });

});
</script>